config/routes.rb
BetTrack::Application.routes.draw do
  get 'bets/finish' => 'bets#finish'
  resources :bets

  resources :sports

  resources :bet_types

  resources :sources
  get 'init/sources' => 'sources#initialize'  

  

end

app/models/source.rb
class Source < ActiveRecord::Base

  def self.initialize
    res = Source.find_by_name 'Wunderdog'
    if res.nil?
      Source.create(name: 'Wunderdog',
                    website: 'http://www.wunderdog.com/',
                    twitter: 'WunderdogSports',
                    trust: 1.00)
    end

    res = Source.find_by_name 'Vegas Runner'
    if res.nil?
      Source.create(name: 'Vegas Runner',
                    website: 'http://www.vegasrunner.com/',
                    twitter: 'VegasRunner',
                    trust: 1.00)

    end

    res = Source.find_by_name 'Prediction Machine'
    if res.nil?
      Source.create(name: 'Prediction Machine',
                    website: 'http://www.predictionmachine.com/',
                    twitter: 'PredictionMachine',
                    trust: 0.50)

    end
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render action: 'show', status: :created, location: @source }
      else
        format.html { render action: 'new' }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url }
      format.json { head :no_content }
    end
  end

  def initialize
    Source.initialize
    #@sources = Source.all
    #render action: 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:name, :website, :twitter, :trust)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :trust %><br>
    <%= f.text_field :trust %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<h1>Listing sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Twitter</th>
      <th>Trust</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.name %></td>
        <td><%= source.website %></td>
        <td><%= source.twitter %></td>
        <td><%= source.trust %></td>
        <td><%= link_to 'Show', source %></td>
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source', new_source_path %>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @source.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @source.website %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @source.twitter %>
</p>

<p>
  <strong>Trust:</strong>
  <%= @source.trust %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>