config/routes.rb
BetTrack::Application.routes.draw do
  get 'bets/finish' => 'bets#finish'
  resources :bets

  resources :sports

  resources :bet_types

  resources :sources
  get 'init/sources' => 'sources#initialize'  

  

end

app/controllers/bet_types_controller.rb
class BetTypesController < ApplicationController
  before_action :set_bet_type, only: [:show, :edit, :update, :destroy]

  # GET /bet_types
  # GET /bet_types.json
  def index
    @bet_types = BetType.all
  end

  # GET /bet_types/1
  # GET /bet_types/1.json
  def show
  end

  # GET /bet_types/new
  def new
    @bet_type = BetType.new
  end

  # GET /bet_types/1/edit
  def edit
  end

  # POST /bet_types
  # POST /bet_types.json
  def create
    @bet_type = BetType.new(bet_type_params)

    respond_to do |format|
      if @bet_type.save
        format.html { redirect_to @bet_type, notice: 'Bet type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bet_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @bet_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bet_types/1
  # PATCH/PUT /bet_types/1.json
  def update
    respond_to do |format|
      if @bet_type.update(bet_type_params)
        format.html { redirect_to @bet_type, notice: 'Bet type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bet_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bet_types/1
  # DELETE /bet_types/1.json
  def destroy
    @bet_type.destroy
    respond_to do |format|
      format.html { redirect_to bet_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet_type
      @bet_type = BetType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_type_params
      params.require(:bet_type).permit(:name)
    end
end

app/helpers/bet_types_helper.rb
module BetTypesHelper
end

app/views/bet_types/_form.html.erb
<%= form_for(@bet_type) do |f| %>
  <% if @bet_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet_type.errors.count, "error") %> prohibited this bet_type from being saved:</h2>

      <ul>
      <% @bet_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bet_types/edit.html.erb
<h1>Editing bet_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet_type %> |
<%= link_to 'Back', bet_types_path %>

app/views/bet_types/index.html.erb
<h1>Listing bet_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bet_types.each do |bet_type| %>
      <tr>
        <td><%= bet_type.name %></td>
        <td><%= link_to 'Show', bet_type %></td>
        <td><%= link_to 'Edit', edit_bet_type_path(bet_type) %></td>
        <td><%= link_to 'Destroy', bet_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet type', new_bet_type_path %>

app/views/bet_types/new.html.erb
<h1>New bet_type</h1>

<%= render 'form' %>

<%= link_to 'Back', bet_types_path %>

app/views/bet_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bet_type.name %>
</p>

<%= link_to 'Edit', edit_bet_type_path(@bet_type) %> |
<%= link_to 'Back', bet_types_path %>