config/routes.rb
BetTrack::Application.routes.draw do
  get 'bets/finish' => 'bets#finish'
  resources :bets

  resources :sports

  resources :bet_types

  resources :sources
  get 'init/sources' => 'sources#initialize'  

  

end

app/models/bet.rb
require 'roo'

class Bet < ActiveRecord::Base
  belongs_to :bet_type
  belongs_to :sport
  belongs_to :source
  belongs_to :bet_result


  def self.load
    ex = Roo::Excelx.new("/home/user/local/src/BetTrack/db/Bets.xlsx")
    ex.default_sheet = ex.sheets.first

    input = InputType.find_by_name("Loaded").id

    2.upto(ex.last_row) do |row_num|
      date  = ex.cell(row_num,1)
      sport = ex.cell(row_num,2)
      source = ex.cell(row_num,3)
      desc = ex.cell(row_num,4)
      amount = ex.cell(row_num,5)
      spread = ex.cell(row_num,6)
      won = ex.cell(row_num,8)

      if won == 'TRUE'
        br = BetResult.find_by_name('Win')          
      elsif won == 'Push'
        br = BetResult.find_by_name('Push')
      elsif won == "FALSE"
        br = BetResult.find_by_name('Loss')
      end

      s = Sport.find_or_create_by(abbrev: sport)
      src = Source.find_or_create_by(abbrev: source)

      Bet.find_or_create_by(
        date: date,
        bet_type_id: nil,
        sport_id: s.id,
        source_id: src.id, 
        description: desc, 
        amount: amount, 
        spread: spread, 
        bet_result_id: (br && br.id) || nil,
        input_type_id: input)
    end
  end
end

app/models/bet_type.rb
class BetType < ActiveRecord::Base

  def self.initialize
    res = BetType.find_by_name 'spread'
    if res.nil?
      BetType.create(name: 'spread')
    end

    res = BetType.find_by_name 'moneyline'
    if res.nil?
      BetType.create(name: 'moneyline')
    end

    res = BetType.find_by_name 'future'
    if res.nil?
      BetType.create(name: 'future')
    end
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bet }
      else
        format.html { render action: 'new' }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url }
      format.json { head :no_content }
    end
  end

  def finish
    @bet = Bet.where(:bet_type_id => nil).order("RANDOM()").limit(1).first
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:date, :bet_type_id, :sport_id, :source_id, :description, :amount, :spread, :bet, :won)
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :bet_type_id %><br>
    <%= collection_select(:bet, :bet_type_id, BetType.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :bet_sport_id %><br>
    <%= collection_select(:bet, :sport_id, Sport.all, :id, :abbrev, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :bet_source_id %><br>
    <%= collection_select(:bet, :source_id, Source.all, :id, :abbrev, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :spread %><br>
    <%= f.text_field :spread %>
  </div>
  <div class="field">
    <%= f.label :bet_input_type_id %><br>
    <%= collection_select(:bet, :input_type_id, InputType.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :bet_bet_result_id %><br>
    <%= collection_select(:bet, :bet_result_id, BetResult.all, :id, :name, prompt: true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/finish.html.erb
<h1>Showing you a random record</h1>

<%= render 'form' %>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Bet type</th>
      <th>Sport</th>
      <th>Source</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Spread</th>
      <th>Bet</th>
      <th>Won</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.date %></td>
        <td><%= bet.bet_type %></td>
        <td><%= bet.sport %></td>
        <td><%= bet.source %></td>
        <td><%= bet.description %></td>
        <td><%= bet.amount %></td>
        <td><%= bet.spread %></td>
        <td><%= bet.bet %></td>
        <td><%= bet.won %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @bet.date %>
</p>

<p>
  <strong>Bet type:</strong>
  <%= @bet.bet_type %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @bet.sport %>
</p>

<p>
  <strong>Source:</strong>
  <%= @bet.source %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bet.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bet.amount %>
</p>

<p>
  <strong>Spread:</strong>
  <%= @bet.spread %>
</p>

<p>
  <strong>Bet:</strong>
  <%= @bet.bet %>
</p>

<p>
  <strong>Won:</strong>
  <%= @bet.won %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>